#!/bin/bash
set -e

RELEASE=1.17.0
JAR_NAME="google-java-format-${RELEASE}-all-deps.jar"
RELEASES_URL=https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format
JAR_URL="${RELEASES_URL}/${RELEASE}/${JAR_NAME}"

CACHE_DIR="$HOME/.cache/google-java-format-git-pre-commit-hook"
JAR_FILE="$CACHE_DIR/$JAR_NAME"
JAR_DOWNLOAD_FILE="${JAR_FILE}.tmp"
JAR_PGP_ASC_FILE="${JAR_FILE}.asc"
PGP_SIGN_KEY_ID=EE0CA873074092F806F59B65D364ABAA39A47320

if [[ ! -f "$JAR_FILE" ]]
then
    mkdir -p "$CACHE_DIR"
    curl -L "$JAR_URL" -o "$JAR_DOWNLOAD_FILE"

    # Downloaded from: "${JAR_URL}.asc"
    cat >"$JAR_PGP_ASC_FILE" <<EOF
-----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEE7gyocwdAkvgG9Ztl02SrqjmkcyAFAmRQI1MACgkQ02Srqjmk
cyDvSA//QceHrVsA9ztoeOBMu1xOMzMzVF8qR7s9bTIH94knvmNb9ivbcs8s9EiN
/0qsbDevEgr8WuWh3QrsmWLTO/+dFePt8/R5EQQohL01B2KMCnRkrYnt03NJsNe+
D1dl1u4e3VCtyQZTpszd9OVAWdBp48xhdeQZxOdgPf/G6ZZuNxs9j/lOoGb5YnKI
AJUDelu5x6YfD3qKG5LOKAe0K/jLmAeDy2Q7bt9xjEMMF2iEboFR8lt7LiE+VK4O
/wzirknMvkoiyR9xJzeZDubQLgmFveDXFn/jtktZJNKtKw9RHLF0keDT4yHcPove
ni4e69FJAdXtrwpWTDcVTYU+XdFZVwUUHfx1UErC57A7Gc0X5uWE8gxruQDJdPEB
mFWeUMEyycje7bPKr5fXLfeCJrW/KGqUPfu14usvj3sbuqKiogyMCzS92dprpkAM
GmBfvCM6KqykEVpUuop4yca4Ny3RIpat+Lu7pr3vEcQ+LtX5b1FiRK5kgmEtwVAL
QuxLCcTmg3UKfp+hCNZin19KtoDgvL4bgSc2FZCx0pWr02xn8Y3PYZgYHMNf7a7u
9FwcbnDp7VYsE1wpnT62X6BDjlEWKrDYqOZNWPC7z/s87BNIvk0AbusMLWQ7PBWH
XKq/N0u18L4n9Kclk4JJcnO2McIFwuzfliTjPND+wJXt5xwW6l4=
=yeSJ
-----END PGP SIGNATURE-----
EOF

    if ! gpg --list-keys "$PGP_SIGN_KEY_ID"
    then
        gpg --keyserver hkps://keyserver.ubuntu.com --recv-key "$PGP_SIGN_KEY_ID"
    fi
    gpg --verify "$JAR_PGP_ASC_FILE" "$JAR_DOWNLOAD_FILE"
    mv "$JAR_DOWNLOAD_FILE" "$JAR_FILE"
fi

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)
if [[ -n "$changed_java_files" ]]
then
    echo "Reformatting Java files: $changed_java_files"
    if ! java   --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
                -jar "$JAR_FILE" --skip-sorting-imports --replace --set-exit-if-changed $changed_java_files
    then
        git add "$changed_java_files"
        echo "An error occurred, aborting commit!" >&2
        exit 1
    fi
else
    echo "No Java files changes found."
fi

cd ./3week/kakao-jpa && ./gradlew build
