name: ci

on: push

jobs:
  format:
    if: github.repository == 'fienestar-assignment/step2-BE-kakao-shop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commitMessage: "format"
  test-and-build:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - run: chmod +x ./gradlew
        working-directory: ./2week/Kakao-Backend-Second-DTO
        shell: bash
      - name: Test and build
        working-directory: ./2week/Kakao-Backend-Second-DTO
        run: ./gradlew build
        shell: bash
